//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate Fluent Mapping template.
// Code is generated on: 11/5/2014 8:26:27 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using FluentNHibernate.Mapping;
using FluentNHibernate.MappingModel.Collections;

namespace NewsApp.Model
{
    /// <summary>
    /// There are no comments for UserSubscriptionMap in the schema.
    /// </summary>
    public partial class UserSubscriptionMap : ClassMap<UserSubscription>
    {
        /// <summary>
        /// There are no comments for UserSubscriptionMap constructor in the schema.
        /// </summary>
        public UserSubscriptionMap()
        {
              Table(@"UserSubscriptions");
              LazyLoad();
              Id(x => x.UserSubscriptionId)
                .Column("UserSubscriptionId")
                .CustomType("Int32")
                .Access.Property()                
                .GeneratedBy.Identity();
              Map(x => x.SubscriptionType)    
                .Column("SubscriptionType")
                .CustomType("String")
                .Access.Property()
                .Generated.Never();
              References(x => x.User)
                .Class<User>()
                .Access.Property()
                .Cascade.None()
                .LazyLoad()
                .Columns("UserId");
              ExtendMapping();
        }

        #region Partial Methods

        partial void ExtendMapping();

        #endregion
    }

}
